apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # -----------------------------------------
      # 1) Scrape do próprio Prometheus
      # -----------------------------------------
      - job_name: 'prometheus'
        static_configs:
          - targets: ['54.204.241.160:5000']

      # -----------------------------------------
      # 2) Scrape da sua aplicação
      # -----------------------------------------
      - job_name: 'devops-app'
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: devops-app-service
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            regex: default
            action: keep

      # -----------------------------------------
      # 3) Scrape de todos os pods do cluster
      # -----------------------------------------
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # mantém apenas pods que expõem a porta  metrics
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            regex: "true"
            action: keep

          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            regex: (.+)
            target_label: __metrics_path__
            action: replace

          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
            regex: (.+)
            target_label: __address__
            action: replace
