apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <html>
      <head><title>Nginx - DevOps Test</title></head>
      <body>
        <h1>Nginx rodando via Kubernetes!</h1>
      </body>
    </html>
